

@startuml Memor Class Diagram

'groups two or more similar arrows together
skinparam groupInheritance 2

'Classes
class DreamJournal 
{
-entryTitle : String
-lastName : String
-phoneNumber : String
-emailAddress : String
-Password : String

#bool createUser(User user)
#String[] readUser(int userId)
#bool updateUser(User user)
#bool deleteUser(int userId)
}


class Account 
{
-userId : int
-accountName : String
-accountType : String
-balance : float 

#bool createAccount(Account account)
#String[] readAccount(int userId)
#bool updateAccount(Account account)
#bool deleteAccount(Account account)  
}


class Transaction 
{
-amount : double
-date : DateTime
-transactionType : String
-category : String
}

class Category
{
-categoryName : String

#int getcategoryId(String categoryName)
#bool createCategory(String category)
}



'Class Relationships (Composition, Aggregation, and Extension/Inheritance [superclass notation])



@enduml