@startuml
object List of Views
}
Welcome
Create Tabia Account (Might be replaced with Google/Apple Sign in)
Habit Dashboard
Create Habit
Edit Habit
}

@startmindmap
* Welcome

** Create Memor Account
*** Dream Journal Entry List
**** New Entry
**** Edit Entry

** Sign In
*** Dream Journal Entry List
**** New Entry
**** Edit Entry
@endmindmap
@enduml
